{!!Html::style('frontend/assets/bootstrap/css/bootstrap.min.css')!!}
{!!Html::style('frontend/assets/css/animate.css')!!}
{!!Html::style('frontend/assets/css/zeynep.css')!!}
{!!Html::style('frontend/assets/css/base.css')!!}
{!!Html::style('frontend/assets/css/owl.carousel.min.css')!!}
{!!Html::style('frontend/assets/css/owl.theme.default.min.css')!!}
{!!Html::style('frontend/assets/icofont/icofont.css')!!}
{!!Html::style('frontend/assets/font-awesome/css/font-awesome.css')!!}
{!!Html::style('frontend/assets/lightbox/dist/css/lightbox.css')!!}
{!!Html::style('frontend/assets/css/style.css')!!}
{!!Html::style('frontend/assets/css/responsive.css')!!}
{!!Html::style('frontend/assets/images/right.png')!!}
